// <auto-generated />
namespace RentACar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addRegularExpressEmail_andEmailtoSopsvenik : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRegularExpressEmail_andEmailtoSopsvenik));
        
        string IMigrationMetadata.Id
        {
            get { return "201912251424184_addRegularExpressEmail_andEmailtoSopsvenik"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
